### ISSUE TITLE
Trigger a reload when HMR doesn't work

### ISSUE THREAD

**Issue by tmeasday** [apollostack/saturn#4]

**Comment by gadicc** [comment]
Hey @tmeasday this looks awesome!

I didn't take a deep look yet but re this issue, presumably you're using `webpack.NoErrorsPlugin()` which prevents a failed HMR from reloading the app (e.g. react-hot-loader prefers to show an error on screen which can be "repaired" by the next HMR).

If that's the case here, some people are doing this:

```js
  if (module.hot) {

    module.hot.addStatusHandler((status) => {
      if (status === "abort") {
        setTimeout(() => process.exit(0), 0);
      }
    });
  }
```

with the server running with `forever`.  Disclaimer: been using webpack for under a week :>  and didn't check all the different HMR statuses.  Saw this in the `react-isomorphic-starterkit` I think.

**Comment by tmeasday** [comment]
It was just a simple option to webpack-hot-middleware in the end, thanks though!

https://github.com/apollostack/saturn/commit/a1777b1fda8d4431488a4fd34be1b4bba0e868b1
